INSERT INTO FAMILY_TREE (FIRST_NAME, MIDDLE_NAME, LAST_NAME, SEX, EMAIL_ADDRESS, STREET_ADDRESS, CITY, STATE, POSTAL_CODE, PHONE_NUMBER, RELATIONSHIP)
VALUES ('NIGEL','K','EARNEST', 'MALE', 'NEARNEST@GMAIL.COM', 'MAIN STREET','WEBSTER', 'MA', '01571', '7775554444', 'SON'),
('SHANNON', 'M', 'MAYO', 'FEMALE', 'SMAYO@GMAIL.COM', 'HAMPTON ROAD', 'POMFRET', 'CT', '06655','8605554444', 'DAUGHTER'),
('SABRINA', 'C', 'VARTERESEN', 'FEMALE', 'SVARTERESEN@GMAIL.COM', 'IDOKNOW RD', 'WEBSTER', 'MA', '12345', '7745212345', 'DAUGHTER'),
('BOSTON', 'C', 'SCHNAUZER', 'MALE', 'BCS@GMAIL.COM', 'ILIVEHERE ST', 'DOGTOWN', 'CT','54321','1234567890', 'SON');

